import { Restaurant } from "@/Type";

// All possible cuisines in the dataset for the filter UI
export const allCuisines = [
  "Indian",
  "Grill",
  "Italian",
  "Fast Food",
  "Japanese",
  "American",
  "Seafood",
];
export const restaurants = [
  {
    id: 1,
    name: "Pizza Palace",
    location: "Dhanmondi",
    cuisines: ["Italian", "Fast Food"],
    deliveryFee: 50,
    discountPercent: 10,
    isOpen: true,
    imageUrl: "/myFood.jpg",
    fastestDelivery: 30,
    distance: 5,
    topRated: 4.3,
    moreInfo: {
      imageUrl: "/myFood.jpg",
      fullLocation:"Shop 35/A Sayed Grand center. House 89,Road 28,Sector 07",
      aboutDeliveryFee:
        "Delivery fee is charged based on time of day and distance.",
      aboutMinimumOrder: "For orders below Tk 100.",
      OpeningHours: [
        "sunday - 10:20 AM - 11:45 PM",
        "monday - 10:20 AM - 11:45 PM",
        "Tuesday - 10:20 AM - 11:45 PM",
        "Wednesday - 10:20 AM - 11:45 PM",
        "Thursday - 10:20 AM - 11:45 PM",
        "Friday - 10:20 AM - 11:45 PM",
      ],
    },
    foods: [
      {
        id: 101,
        name: "Margherita Pizza",
        description: "Classic pizza with tomato, mozzarella, and basil",
        price: 550,
        category: "Pizza",
        isAvailable: true,
        isVeg: true,
        calories: 800,
        imageUrl: "/myFood.jpg",
      },
      {
        id: 102,
        name: "BBQ Chicken Pizza",
        description: "Tangy BBQ sauce, grilled chicken, onions, and cheese",
        price: 750,
        category: "Pizza",
        isAvailable: true,
        isVeg: false,
        calories: 950,
        imageUrl: "/myFood.jpg",
      },
      {
        id: 103,
        name: "Veggie Supreme Pizza",
        description: "Loaded with mushrooms, bell peppers, and olives",
        price: 670,
        category: "Pizza",
        isAvailable: true,
        isVeg: true,
        calories: 720,
        imageUrl: "/myFood.jpg",
      },
    ],
  },
  {
    id: 2,
    name: "Burger House",
    location: "Banani",
    cuisines: ["American", "Fast Food"],
    deliveryFee: 40,
    discountPercent: 12,
    isOpen: false,
    imageUrl: "/myFood.jpg",
    fastestDelivery: 15,
    distance: 2,
    topRated: 3.3,
    moreInfo: {
      imageUrl: "/myFood.jpg",
      fullLocation:"Shop 35/A Sayed Grand center. House 89,Road 28,Sector 07",
      aboutDeliveryFee:
        "Delivery fee is charged based on time of day and distance.",
      aboutMinimumOrder: "For orders below Tk 100.",
      OpeningHours: [
        "sunday - 10:20 AM - 11:45 PM",
        "monday - 10:20 AM - 11:45 PM",
        "Tuesday - 10:20 AM - 11:45 PM",
        "Wednesday - 10:20 AM - 11:45 PM",
        "Thursday - 10:20 AM - 11:45 PM",
        "Friday - 10:20 AM - 11:45 PM",
      ],
    },
    foods: [
      {
        id: 201,
        name: "Classic Beef Burger",
        description: "Juicy beef patty with lettuce, tomato, and house sauce",
        price: 350,
        category: "Burger",
        isAvailable: true,
        isVeg: false,
        calories: 700,
        imageUrl: "/images/beef-burger.jpg",
      },
      {
        id: 202,
        name: "Cheesy Chicken Burger",
        description: "Fried chicken breast with melted cheese and mayo",
        price: 320,
        category: "Burger",
        isAvailable: false,
        isVeg: false,
        calories: 680,
        imageUrl: "/myFood.jpg",
      },
      {
        id: 203,
        name: "Spicy Veg Burger",
        description: "Spicy veg patty with lettuce and creamy sauce",
        price: 290,
        category: "Burger",
        isAvailable: true,
        isVeg: true,
        calories: 650,
        imageUrl: "/myFood.jpg",
      },
    ],
  },
  {
    id: 3,
    name: "Sushi World",
    location: "Gulshan",
    cuisines: ["Japanese", "Seafood"],
    deliveryFee: 70,
    discountPercent: 15,
    isOpen: true,
    imageUrl: "/myFood.jpg",
    fastestDelivery: 40,
    distance: 8,
    topRated: 4.9,
    moreInfo: {
      imageUrl: "/myFood.jpg",
      fullLocation:"Shop 35/A Sayed Grand center. House 89,Road 28,Sector 07",
      aboutDeliveryFee:
        "Delivery fee is charged based on time of day and distance.",
      aboutMinimumOrder: "For orders below Tk 100.",
      OpeningHours: [
        "sunday - 10:20 AM - 11:45 PM",
        "monday - 10:20 AM - 11:45 PM",
        "Tuesday - 10:20 AM - 11:45 PM",
        "Wednesday - 10:20 AM - 11:45 PM",
        "Thursday - 10:20 AM - 11:45 PM",
        "Friday - 10:20 AM - 11:45 PM",
      ],
    },
    foods: [
      {
        id: 301,
        name: "Salmon Nigiri",
        description: "Fresh salmon over vinegared rice",
        price: 900,
        category: "Sushi",
        isAvailable: true,
        isVeg: false,
        calories: 300,
        imageUrl: "/myFood.jpg",
      },
      {
        id: 302,
        name: "Tuna Maki Roll",
        description: "Tuna wrapped in seasoned rice and seaweed",
        price: 850,
        category: "Sushi",
        isAvailable: true,
        isVeg: false,
        calories: 280,
        imageUrl: "/myFood.jpgg",
      },
      {
        id: 303,
        name: "Avocado Sushi",
        description: "Creamy avocado in sticky rice and nori",
        price: 780,
        category: "Sushi",
        isAvailable: true,
        isVeg: true,
        calories: 260,
        imageUrl: "/myFood.jpg",
      },
    ],
  },
  {
    id: 4,
    name: "Biryani Express",
    location: "Mohammadpur",
    cuisines: ["Bangladeshi", "Mughlai"],
    deliveryFee: 30,
    discountPercent: 0,
    isOpen: true,
    imageUrl: "/myFood.jpg",
    fastestDelivery: 50,
    distance: 7,
    topRated: 2.3,
    moreInfo: {
      imageUrl: "/myFood.jpg",
      fullLocation:"Shop 35/A Sayed Grand center. House 89,Road 28,Sector 07",
      aboutDeliveryFee:
        "Delivery fee is charged based on time of day and distance.",
      aboutMinimumOrder: "For orders below Tk 100.",
      OpeningHours: [
        "sunday - 10:20 AM - 11:45 PM",
        "monday - 10:20 AM - 11:45 PM",
        "Tuesday - 10:20 AM - 11:45 PM",
        "Wednesday - 10:20 AM - 11:45 PM",
        "Thursday - 10:20 AM - 11:45 PM",
        "Friday - 10:20 AM - 11:45 PM",
      ],
    },
    foods: [
      {
        id: 401,
        name: "Kacchi Biryani",
        description: "Traditional kacchi with tender mutton and fragrant rice",
        price: 420,
        category: "Biryani",
        isAvailable: true,
        isVeg: false,
        calories: 1200,
        imageUrl: "/myFood.jpg",
      },
      {
        id: 402,
        name: "Chicken Tehari",
        description: "Spicy chicken tehari served with salad",
        price: 380,
        category: "Biryani",
        isAvailable: true,
        isVeg: false,
        calories: 1100,
        imageUrl: "/myFood.jpg",
      },
      {
        id: 403,
        name: "Vegetable Pulao",
        description: "Light and fluffy rice with vegetables",
        price: 300,
        category: "Rice",
        isAvailable: true,
        isVeg: true,
        calories: 600,
        imageUrl: "/myFood.jpg",
      },
    ],
  },
  {
    id: 5,
    name: "Tandoori Flames",
    location: "Uttara",
    cuisines: ["Indian", "Grill"],
    deliveryFee: 45,
    discountPercent: 5,
    isOpen: false,
    imageUrl: "/myFood.jpg",
    fastestDelivery: 20,
    distance: 1,
    topRated: 5.0,
    moreInfo: {
      imageUrl: "/myFood.jpg",
      fullLocation:"Shop 35/A Sayed Grand center. House 89,Road 28,Sector 07",
      aboutDeliveryFee:
        "Delivery fee is charged based on time of day and distance.",
      aboutMinimumOrder: "For orders below Tk 100.",
      OpeningHours: [
        "sunday - 10:20 AM - 11:45 PM",
        "monday - 10:20 AM - 11:45 PM",
        "Tuesday - 10:20 AM - 11:45 PM",
        "Wednesday - 10:20 AM - 11:45 PM",
        "Thursday - 10:20 AM - 11:45 PM",
        "Friday - 10:20 AM - 11:45 PM",
      ],
    },
    foods: [
      {
        id: 501,
        name: "Tandoori Chicken",
        description: "Grilled chicken marinated with Indian spices",
        price: 480,
        category: "Grill",
        isAvailable: true,
        isVeg: false,
        calories: 950,
        imageUrl: "/myFood.jpg",
      },
      {
        id: 502,
        name: "Paneer Tikka",
        description: "Chunks of paneer grilled with capsicum and spices",
        price: 420,
        category: "Grill",
        isAvailable: true,
        isVeg: true,
        calories: 650,
        imageUrl: "/myFood.jpg",
      },
      {
        id: 503,
        name: "Butter Naan",
        description: "Soft naan bread topped with butter",
        price: 70,
        category: "Bread",
        isAvailable: true,
        isVeg: true,
        calories: 250,
        imageUrl: "/myFood.jpg",
      },
    ],
  },
];

export const FavouriteCuisinesData = [
  {
    title: "Biryani",
    imageUrl: "/myFood.jpg",
  },
  {
    title: "Burger",
    imageUrl: "/myFood.jpg",
  },
  {
    title: "Pizza",
    imageUrl: "/myFood.jpg",
  },
  {
    title: "Chicken",
    imageUrl: "/myFood.jpg",
  },
  {
    title: "Fast Food",
    imageUrl: "/myFood.jpg",
  },
  {
    title: "Pasta",
    imageUrl: "/myFood.jpg",
  },
];
export const DailyDealsData = [
  {
    title: "Biryani",
    imageUrl: "/DailyDealsImage.jpg",
  },
  {
    title: "Burger",
    imageUrl: "/DailyDealsImage.jpg",
  },
  {
    title: "Pizza",
    imageUrl: "/DailyDealsImage.jpg",
  },
  {
    title: "Chicken",
    imageUrl: "/DailyDealsImage.jpg",
  },
  {
    title: "Fast Food",
    imageUrl: "/DailyDealsImage.jpg",
  },
  {
    title: "Pasta",
    imageUrl: "/DailyDealsImage.jpg",
  },
];

export const newFood = [
  {
    id: 1,
    restaurantName: "Pizza Palace",
    location: "Dhanmondi",
    rating: 4.3,
    ratingPersons: 200,
    deliveryFee: 50,
    deliveryTime: "10-40 min",
    cuisines: ["Italian", "Fast Food"],
    discountPercent: 10,
    minimumOrder: 100,
    isOpen: true,
    imageUrl: "/myFood.jpg",
    moreInfo: {
      imageUrl: "/myFood.jpg",
      fullLocation:"Shop 35/A Sayed Grand center. House 89,Road 28,Sector 07",
      aboutDeliveryFee:
        "Delivery fee is charged based on time of day and distance.",
      aboutMinimumOrder: "For orders below Tk 100.",
      OpeningHours: [
        "sunday - 10:20 AM - 11:45 PM",
        "monday - 10:20 AM - 11:45 PM",
        "Tuesday - 10:20 AM - 11:45 PM",
        "Wednesday - 10:20 AM - 11:45 PM",
        "Thursday - 10:20 AM - 11:45 PM",
        "Friday - 10:20 AM - 11:45 PM",
      ],
    },
    foods: [
      {
        id: 101,
        name: "Margherita Pizza",
        description: "Classic pizza with tomato, mozzarella, and basil",
        previousPrice: 550,
        currentPrice: 450,
        category: "Pizza",
        isAvailable: true,
        isVeg: true,
        calories: 800,
        imageUrl: "/myFood.jpg",
      },
      {
        id: 102,
        name: "BBQ Chicken Pizza",
        description: "Tangy BBQ sauce, grilled chicken, onions, and cheese",
        price: 750,
        category: "Pizza",
        isAvailable: true,
        isVeg: false,
        calories: 950,
        imageUrl: "/myFood.jpg",
      },
      {
        id: 103,
        name: "Veggie Supreme Pizza",
        description: "Loaded with mushrooms, bell peppers, and olives",
        price: 670,
        category: "Pizza",
        isAvailable: true,
        isVeg: true,
        calories: 720,
        imageUrl: "/myFood.jpg",
      },
    ],
  },
];
